---
previous_task_names:
    - gen_reports/gen_model_tables
    - gen_reports/gen_plots

render_input: src/generate_report_doc.R

render_output_format: pdf_document

render_output_file: parole_forums_report

render_knit_root_dir: ..

render_output_dir: output

table_3:
    comp_tables:
        - table_5
        - table_a2
    caption: Effect of being called in to attend forums
    note:
    align: lccccc
    column_spec:
        width:
            - 4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
        unit: cm
    row_spec_rows:
        - 5
        - 10
        - 15
        - 20
        - 25
        - 30
    header:
        labels:
            - ' '
            - ITT Effect
            - TOT Effect
        colspan:
            - 2
            - 2
            - 2

table_4:
    comp_tables:
        - table_6
        - table_8
    caption: >-
        Effect within 1 year of being called in to attend forums for specific
        subgroup
    note:
    align: lcccccc
    column_spec:
        width:
            - 4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
        unit: cm
    row_spec_rows:
        - 2
        - 6
    header:
        labels:
            - ' '
            - Under Age 30
            - At Least 2 Weapons Charges
        colspan:
            - 1
            - 3
            - 3

table_4b:
    comp_tables:
        - table_6b
        - table_8b
    caption: >-
        Effect within 6 months of being called in to attend forums for specific
        subgroup
    note:
    align: lcccccc
    column_spec:
        width:
            - 4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
        unit: cm
    row_spec_rows:
        - 2
        - 6
    header:
        labels:
            - ' '
            - Under Age 30
            - At Least 2 Weapons Charges
        colspan:
            - 1
            - 3
            - 3

table_5:
    comp_tables:
        - table_9
    caption: >-
        Effect within 1 year of being called in to attend forums by program
        site
    note:
    align: lcccc
    column_spec:
        width:
            - 4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
        unit: cm
    row_spec_rows:
        - 5
        - 10
        - 15
        - 20
        - 25

table_5b:
    comp_tables:
        - table_9b
    caption: >-
        Effect within 6 months of being called in to attend forums by program
        site
    note:
    align: lcccc
    column_spec:
        width:
            - 4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
        unit: cm
    row_spec_rows:
        - 5
        - 10
        - 15
        - 20
        - 25

table_6:
    comp_tables:
        - table_10
    caption: >-
        Effect of living in treatment neighborhood, but not being called in to
        attend forums
    note:
    align: lccc
    column_spec:
        width:
            - 4
            - 1.4
            - 1.4
            - 1.4
        unit: cm
    row_spec_rows:
        - 5
        - 10
        - 15
        - 20
        - 25
        - 30

table_6b:
    comp_tables:
        - table_10b
    caption: >-
        Effect of living in a treatment neighborhood and being called in to
        attend forums
    note:
    align: lccc
    column_spec:
        width:
            - 4
            - 1.4
            - 1.4
            - 1.4
        unit: cm
    row_spec_rows:
        - 5
        - 10
        - 15
        - 20
        - 25
        - 30

table_7:
    comp_tables:
        - table_11
    caption: Effect of program on neighborhood-level crimes
    note:
    align: lccc
    column_spec:
        width:
            - 5
            - 1.4
            - 1.4
            - 1.4
        unit: cm
    row_spec_rows:
        - 2
        - 4
        - 6
        - 8
        - 10

table_8:
    comp_tables:
        - table_5_truncated
        - table_a2_truncated
    caption: >-
        Effect of being called in to attend forums - truncated
        follow-up period
    note:
    align: lccccc
    column_spec:
        width:
            - 4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
            - 1.4
        unit: cm
    row_spec_rows:
        - 4
        - 8
        - 12
        - 16
        - 20
    header:
        labels:
            - ' '
            - ITT Effect
            - TOT Effect
        colspan:
            - 2
            - 2
            - 2

